version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata_projeto2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: novoprojetodb
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata_projeto2: