server:
  port: 8080
#  use-forward-headers: true
  servlet.context-path: /api/project_a


sga:
  auth:
    jwtSecret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MDA3MDcwMTEsImV4cCI6MTczMjI0MzAxMSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.RML0oFMmJxZ6TpgYrTpGLCbXo1CD7jaGCRVcHTGwuSMXEtbtNzU9OXAOqShjkl_sL0gENYfBT6K3PxCR6LQrrw
    jwtExpirationMs: 31536000000